import json
from pathlib import Path

p = Path(__file__).resolve().parents[1] / "data" / "seed_opportunities.json"
data = json.loads(p.read_text(encoding="utf-8"))
by_id = {x["id"]: x for x in data}

if "in-aicte-pragati" in by_id:
    by_id["in-aicte-pragati"]["eligibility"]["gender"] = ["female", "girl", "woman"]
if "in-british-council-ielts" in by_id:
    by_id["in-british-council-ielts"]["description"] = (
        "British Council India lists currently open Study UK / IELTS-related awards on this page. "
        "Only apply to awards that show an open Apply button and deadline — ignore expired campaigns."
    )

extra = [
    {
        "id": "in-digital-gujarat",
        "title": "Digital Gujarat Scholarship Portal (State Schemes)",
        "provider": "Government of Gujarat",
        "opportunity_type": "scholarship",
        "description": "Official Gujarat state scholarship portal for multiple state schemes. Students at Gujarat colleges (e.g. Parul University) apply here when the annual window is open.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-07-01",
        "location": "Gujarat, India",
        "eligibility_text": "Students studying in Gujarat meeting scheme-specific caste/income/merit rules.",
        "required_documents": ["aadhaar", "income_certificate", "caste_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://www.digitalgujarat.gov.in/",
        "application_url": "https://www.digitalgujarat.gov.in/",
        "source_name": "Digital Gujarat",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma", "school"],
            "countries": ["IN", "India"],
            "states": ["gujarat", "gj"],
        },
    },
    {
        "id": "in-mysy-gujarat",
        "title": "Mukhyamantri Yuva Swavalamban Yojana (MYSY) — Gujarat",
        "provider": "Government of Gujarat",
        "opportunity_type": "scholarship",
        "description": "Gujarat state merit-cum-means support scheme. Apply via official MYSY when open.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-07-01",
        "location": "Gujarat, India",
        "eligibility_text": "Gujarat domicile students meeting MYSY merit and income criteria.",
        "required_documents": ["aadhaar", "income_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://mysy.guj.nic.in/",
        "application_url": "https://mysy.guj.nic.in/",
        "source_name": "MYSY Gujarat",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "diploma"],
            "countries": ["IN", "India"],
            "states": ["gujarat", "gj"],
        },
    },
    {
        "id": "in-mahadbt",
        "title": "MahaDBT — Maharashtra State Scholarships",
        "provider": "Government of Maharashtra",
        "opportunity_type": "scholarship",
        "description": "Official Maharashtra DBT portal for multiple state scholarship schemes.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-07-01",
        "location": "Maharashtra, India",
        "eligibility_text": "Maharashtra domicile / studying-in-state students as per each scheme.",
        "required_documents": ["aadhaar", "income_certificate", "caste_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://mahadbt.maharashtra.gov.in/",
        "application_url": "https://mahadbt.maharashtra.gov.in/",
        "source_name": "MahaDBT",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma", "school"],
            "countries": ["IN", "India"],
            "states": ["maharashtra", "mh"],
        },
    },
    {
        "id": "in-egrantz-kerala",
        "title": "e-Grantz — Kerala Post-Matric Scholarships",
        "provider": "Government of Kerala",
        "opportunity_type": "scholarship",
        "description": "Kerala official e-Grantz portal for post-matric scholarships.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-11-30",
        "application_start_date": "2026-07-01",
        "location": "Kerala, India",
        "eligibility_text": "Kerala students meeting community/income criteria for e-Grantz.",
        "required_documents": ["aadhaar", "income_certificate", "caste_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://www.egrantz.kerala.gov.in/",
        "application_url": "https://www.egrantz.kerala.gov.in/",
        "source_name": "e-Grantz Kerala",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma"],
            "countries": ["IN", "India"],
            "states": ["kerala", "kl"],
        },
    },
    {
        "id": "in-epass-telangana",
        "title": "Telangana ePASS Scholarships",
        "provider": "Government of Telangana",
        "opportunity_type": "scholarship",
        "description": "Official Telangana ePASS portal for post-matric scholarships.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-07-01",
        "location": "Telangana, India",
        "eligibility_text": "Telangana students meeting ePASS caste/income criteria.",
        "required_documents": ["aadhaar", "income_certificate", "caste_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://telanganaepass.cgg.gov.in/",
        "application_url": "https://telanganaepass.cgg.gov.in/",
        "source_name": "Telangana ePASS",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma"],
            "countries": ["IN", "India"],
            "states": ["telangana", "ts"],
        },
    },
    {
        "id": "in-epass-ap",
        "title": "Andhra Pradesh Jnanabhumi Scholarships",
        "provider": "Government of Andhra Pradesh",
        "opportunity_type": "scholarship",
        "description": "Official AP Jnanabhumi scholarship services for post-matric / fee reimbursement.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-07-01",
        "location": "Andhra Pradesh, India",
        "eligibility_text": "Andhra Pradesh students meeting Jnanabhumi scheme rules.",
        "required_documents": ["aadhaar", "income_certificate", "caste_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://jnanabhumi.ap.gov.in/",
        "application_url": "https://jnanabhumi.ap.gov.in/",
        "source_name": "Jnanabhumi AP",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma"],
            "countries": ["IN", "India"],
            "states": ["andhra pradesh", "ap"],
        },
    },
    {
        "id": "in-ssp-karnataka",
        "title": "State Scholarship Portal (SSP) — Karnataka",
        "provider": "Government of Karnataka",
        "opportunity_type": "scholarship",
        "description": "Karnataka SSP for post-matric and related schemes.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-07-01",
        "location": "Karnataka, India",
        "eligibility_text": "Karnataka students meeting SSP scheme eligibility.",
        "required_documents": ["aadhaar", "income_certificate", "caste_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://ssp.postmatric.karnataka.gov.in/",
        "application_url": "https://ssp.postmatric.karnataka.gov.in/",
        "source_name": "SSP Karnataka",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma"],
            "countries": ["IN", "India"],
            "states": ["karnataka", "ka"],
        },
    },
    {
        "id": "in-up-scholarship",
        "title": "UP Scholarship Portal",
        "provider": "Government of Uttar Pradesh",
        "opportunity_type": "scholarship",
        "description": "Official Uttar Pradesh scholarship portal for pre/post-matric schemes.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-12-31",
        "application_start_date": "2026-07-01",
        "location": "Uttar Pradesh, India",
        "eligibility_text": "UP domicile students meeting scheme criteria.",
        "required_documents": ["aadhaar", "income_certificate", "caste_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://scholarship.up.gov.in/",
        "application_url": "https://scholarship.up.gov.in/",
        "source_name": "UP Scholarship",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma", "school"],
            "countries": ["IN", "India"],
            "states": ["uttar pradesh", "up"],
        },
    },
    {
        "id": "in-mp-scholarship",
        "title": "MP Scholarship Portal",
        "provider": "Government of Madhya Pradesh",
        "opportunity_type": "scholarship",
        "description": "Madhya Pradesh official scholarship portal.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-07-01",
        "location": "Madhya Pradesh, India",
        "eligibility_text": "MP students meeting portal scheme eligibility.",
        "required_documents": ["aadhaar", "income_certificate", "caste_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://scholarshipportal.mp.nic.in/",
        "application_url": "https://scholarshipportal.mp.nic.in/",
        "source_name": "MP Scholarship Portal",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma"],
            "countries": ["IN", "India"],
            "states": ["madhya pradesh", "mp"],
        },
    },
    {
        "id": "in-wb-oasis",
        "title": "OASIS — West Bengal Scholarships",
        "provider": "Government of West Bengal",
        "opportunity_type": "scholarship",
        "description": "Official OASIS portal for West Bengal scholarships.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-11-30",
        "application_start_date": "2026-07-01",
        "location": "West Bengal, India",
        "eligibility_text": "West Bengal students meeting OASIS scheme rules.",
        "required_documents": ["aadhaar", "income_certificate", "caste_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://oasis.gov.in/",
        "application_url": "https://oasis.gov.in/",
        "source_name": "OASIS WB",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma"],
            "countries": ["IN", "India"],
            "states": ["west bengal", "wb"],
        },
    },
    {
        "id": "in-aicte-swanath",
        "title": "AICTE Swanath Scholarship",
        "provider": "AICTE / NSP",
        "opportunity_type": "scholarship",
        "description": "AICTE Swanath for eligible special-category students in AICTE-approved programmes. Apply via NSP.",
        "amount": 50000,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-06-01",
        "location": "India",
        "eligibility_text": "Students in AICTE-approved programmes meeting Swanath criteria.",
        "required_documents": ["aadhaar", "income_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://www.aicte-india.org/schemes/students-development-schemes",
        "application_url": "https://scholarships.gov.in/ApplicationForm",
        "source_name": "AICTE via NSP",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "diploma"],
            "countries": ["IN", "India"],
            "fields": ["engineering", "technology"],
        },
    },
    {
        "id": "in-aicte-pg-scholarship",
        "title": "AICTE PG Scholarship (GATE/GPAT)",
        "provider": "AICTE",
        "opportunity_type": "scholarship",
        "description": "PG scholarship support for GATE/GPAT qualified students in AICTE-approved programmes.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-06-01",
        "location": "India",
        "eligibility_text": "GATE/GPAT qualified PG students in AICTE-approved institutions.",
        "required_documents": ["aadhaar", "gate_scorecard", "transcript", "bank_passbook"],
        "official_source_url": "https://www.aicte-india.org/schemes/students-development-schemes",
        "application_url": "https://www.aicte-india.org/schemes/students-development-schemes",
        "source_name": "AICTE",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["masters"],
            "countries": ["IN", "India"],
            "fields": ["engineering", "technology", "pharmacy"],
        },
    },
    {
        "id": "in-top-class-sc",
        "title": "Top Class Education Scheme for SC Students",
        "provider": "Ministry of Social Justice / NSP",
        "opportunity_type": "scholarship",
        "description": "Central scheme for SC students in notified top-class institutions via NSP.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-06-01",
        "location": "India",
        "eligibility_text": "SC students admitted to notified institutions meeting income criteria.",
        "required_documents": ["aadhaar", "caste_certificate", "income_certificate", "transcript", "admission_letter"],
        "official_source_url": "https://scholarships.gov.in/Students",
        "application_url": "https://scholarships.gov.in/ApplicationForm",
        "source_name": "NSP",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters"],
            "countries": ["IN", "India"],
            "category": ["SC"],
        },
    },
    {
        "id": "in-sitaram-jindal",
        "title": "Sitaram Jindal Foundation Scholarship",
        "provider": "Sitaram Jindal Foundation",
        "opportunity_type": "scholarship",
        "description": "Merit-cum-means scholarship. Apply on the official foundation scholarship page when open.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-12-31",
        "application_start_date": "2026-01-01",
        "location": "India",
        "eligibility_text": "Indian students meeting foundation academic and income criteria.",
        "required_documents": ["aadhaar", "income_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://www.sitaramjindalfoundation.org/",
        "application_url": "https://www.sitaramjindalfoundation.org/scholarships.html",
        "source_name": "Sitaram Jindal Foundation",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["bachelors", "masters", "diploma", "school"],
            "countries": ["IN", "India"],
        },
    },
    {
        "id": "in-csir-jrf",
        "title": "CSIR-UGC NET JRF / Research Fellowships",
        "provider": "CSIR-HRDG",
        "opportunity_type": "fellowship",
        "description": "Research fellowships for NET-qualified candidates via official CSIR HRDG.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-12-31",
        "application_start_date": "2026-01-01",
        "location": "India",
        "eligibility_text": "Candidates with CSIR-UGC NET / equivalent as notified.",
        "required_documents": ["transcript", "resume", "research_proposal"],
        "official_source_url": "https://csirhrdg.res.in/",
        "application_url": "https://csirhrdg.res.in/",
        "source_name": "CSIR-HRDG",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["masters", "phd"],
            "countries": ["IN", "India"],
            "fields": ["science", "engineering", "technology"],
        },
    },
    {
        "id": "in-begum-hazrat-mahal",
        "title": "Begum Hazrat Mahal National Scholarship",
        "provider": "Maulana Azad Education Foundation / NSP",
        "opportunity_type": "scholarship",
        "description": "Scholarship for girl students from minority communities via NSP when listed.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-06-01",
        "location": "India",
        "eligibility_text": "Girl students from notified minority communities.",
        "required_documents": ["aadhaar", "income_certificate", "community_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://scholarships.gov.in/Students",
        "application_url": "https://scholarships.gov.in/ApplicationForm",
        "source_name": "NSP",
        "source_verified": True,
        "status": "open",
        "eligibility": {
            "education_level": ["school", "bachelors"],
            "countries": ["IN", "India"],
            "gender": ["female", "girl", "woman"],
        },
    },
    {
        "id": "in-prematric-minority",
        "title": "Pre-Matric Scholarship for Minorities",
        "provider": "Ministry of Minority Affairs / NSP",
        "opportunity_type": "scholarship",
        "description": "Central pre-matric scholarship for minority communities via NSP.",
        "amount": None,
        "currency": "INR",
        "deadline": "2026-10-31",
        "application_start_date": "2026-06-01",
        "location": "India",
        "eligibility_text": "Minority community school students meeting income criteria.",
        "required_documents": ["aadhaar", "income_certificate", "community_certificate", "transcript", "bank_passbook"],
        "official_source_url": "https://scholarships.gov.in/Students",
        "application_url": "https://scholarships.gov.in/ApplicationForm",
        "source_name": "NSP",
        "source_verified": True,
        "status": "open",
        "eligibility": {"education_level": ["school"], "countries": ["IN", "India"]},
    },
]

for item in extra:
    by_id[item["id"]] = item

out = list(by_id.values())
p.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print("total", len(out), "open", sum(1 for x in out if x.get("status") == "open"))
